INSERT INTO movies_animated VALUES (NULL, 'Sausage Party', 'Conrad Vernon', 2016, 5, 'A raunchy and hilarious animated movie about food products.', 18);
INSERT INTO movies_animated VALUES (NULL, 'South Park: Bigger, Longer & Uncut', 'Trey Parker', 1999, 7, 'An irreverent and satirical musical comedy based on the TV show.', 17);
INSERT INTO movies_animated VALUES (NULL, 'Anomalisa', 'Charlie Kaufman', 2015, 8, 'A quirky and introspective stop-motion movie about a motivational speaker.', 16);
INSERT INTO movies_animated VALUES (NULL, 'Watership Down', 'Martin Rosen', 1978, 7, 'An intense and violent adaptation of the classic novel about rabbits.', 13);
INSERT INTO movies_animated VALUES (NULL, 'Grave of the Fireflies', 'Isao Takahata', 1988, 9, 'A heartbreaking and sobering Japanese anime movie about two siblings during World War II.', 16);
INSERT INTO movies_animated VALUES (NULL, 'Toy Story', 'John Lasseter', 1995, 9, 'The first feature-length computer-animated movie.', 0);
INSERT INTO movies_animated VALUES (NULL, 'The Lion King', 'Roger Allers', 1994, 8, 'One of the most beloved animated movies of all time.', 0);
INSERT INTO movies_animated VALUES (NULL, 'Finding Nemo', 'Andrew Stanton', 2003, 9, 'A heartwarming story about a father looking for his son.', 0);
INSERT INTO movies_animated VALUES (NULL, 'Inside Out', 'Pete Docter', 2015, 8, 'A creative and emotional exploration of the mind.', 0);
INSERT INTO movies_animated VALUES (NULL, 'Zootopia', 'Byron Howard', 2016, 7, 'A fun and socially relevant movie about a world of anthropomorphic animals.', 0);
INSERT INTO movies_animated VALUES (NULL, 'Moana', 'Ron Clements', 2016, 8, 'A visually stunning adventure inspired by Polynesian mythology.', 0);
INSERT INTO movies_animated VALUES (NULL, 'The Incredibles', 'Brad Bird', 2004, 9, 'A superhero movie with a family twist.', 0);
INSERT INTO movies_animated VALUES (NULL, 'WALL-E', 'Andrew Stanton', 2008, 9, 'A beautiful and thought-provoking love story set in a dystopian future.', 0);
INSERT INTO movies_animated VALUES (NULL, 'Up', 'Pete Docter', 2009, 8, 'A touching and funny adventure about an elderly man and a young boy.', 0);
INSERT INTO movies_animated VALUES (NULL, 'The Little Mermaid', 'Ron Clements', 1989, 7, 'A classic fairy tale with catchy songs.', 0);
